version: 1
accounts:
  - name: alice
    coins: ["10000000000uatom", "500000000000uusd", "10000000000stake"]
  - name: bob
    coins: ["10000000000uatom"]
validator:
  name: alice
  staked: "1000000000stake"
client:
  vuex:
    path: "vue"